name: editor_image
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ffi: ^2.1.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  image: ^4.5.4
  dartz: ^0.10.1
  pigeon: ^25.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  ffigen: ^18.1.0
  mockito: ^5.4.6

flutter:
  uses-material-design: true
